tailscale: ENC[AES256_GCM,data:XmaXd8ut1y1KjV8Kr3W0P7/p4hB+dT0kqIMVKhCuJUYkGfGVGTIRzOB9AfQsgNP5nfWZiFeXtrsWGReCQ64=,iv:MHsoTNXT8kx69f+Z5zY9UrT/equreuJh1Xo/iBP9Rjo=,tag:8K6u1MNZoCrJnzzu2Yupuw==,type:str]
users:
    joshua: ENC[AES256_GCM,data:T2toJkrGFOKMtB8ZG+WIjlBd0cVLgITA1JMLUEOlfHcepj/zs/6kr5c9/Hns4nQmkXWpxiPVXqvjS81oLmpkpDwGuCT55eOp2A==,iv:oGKaMu460C09HUPuoo9Int7MKBT2u+3v27vDbveTdTU=,tag:YrHiH+b78qzWWUIVO0+AZA==,type:str]
sops:
    age:
        - recipient: age1de6wyynhrf0mjxg85dq8layuwqudj527pfv9l4v6sdcu8a5w0ggqedl40j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK25nN2k1cWRqNzhaclBH
            ZjN3WGhYcmh1aXZWOFRQdmJnNjVqV1Fmd2djCmVFSWdpWERXZ0dDcmdkVEQ3NmIx
            Qk1lL0pWRkVKaVc1SjZYU3ZoOEFlaDgKLS0tIFg5dU5JSUxqTWZPcmVVZVl3bkRj
            TlowR011S0p4MDQwMThNb2xIUjI5NUEKs6E1zb9PbJm06Lso9zxsa5PRjEIOGi9z
            g97FC415NBptevFpWtoa83PAIdW0IOtstSx9v6zVMgxMFVGFt7Q8pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-15T23:21:35Z"
    mac: ENC[AES256_GCM,data:/eHRtUKfVw5xc50ct8gWUuRdF4eeJ/eF6AwqOhoytl7uONi7fdX0swpwkYGPAICXUDeZkOpgnnrAaDYldwX9dyF3Y8W0BlegBFWJPQTTjq/YAaJucUh43syCUKb5MjN+w+MIyXzToSqjDvNHXzHN6lpEomoz/6d3Q0JH4asAEAU=,iv:GsuH7noY2eaxPykH4dPekTm2aHR0e8VxtrVhy9P3QN8=,tag:umezWCByc7A15YkJDecy9Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
