potato: ENC[AES256_GCM,data:Faq51Q==,iv:f9pke1G8RVZ7Fr+yytPUEHbBlqawjMMmf3rrR7LoJAY=,tag:ZRSsVttketr6LmJ3ZiPu8Q==,type:str]
users:
    joshua: ENC[AES256_GCM,data:T2toJkrGFOKMtB8ZG+WIjlBd0cVLgITA1JMLUEOlfHcepj/zs/6kr5c9/Hns4nQmkXWpxiPVXqvjS81oLmpkpDwGuCT55eOp2A==,iv:oGKaMu460C09HUPuoo9Int7MKBT2u+3v27vDbveTdTU=,tag:YrHiH+b78qzWWUIVO0+AZA==,type:str]
    fake: ENC[AES256_GCM,data:FqmWBwET/g==,iv:UEhJkQWjHEs7sCWGz1C+E5acUQWBxr7gsb2MpgjxQeA=,tag:J6qlHPqXc8m+8qHjTKFUhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1de6wyynhrf0mjxg85dq8layuwqudj527pfv9l4v6sdcu8a5w0ggqedl40j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK25nN2k1cWRqNzhaclBH
            ZjN3WGhYcmh1aXZWOFRQdmJnNjVqV1Fmd2djCmVFSWdpWERXZ0dDcmdkVEQ3NmIx
            Qk1lL0pWRkVKaVc1SjZYU3ZoOEFlaDgKLS0tIFg5dU5JSUxqTWZPcmVVZVl3bkRj
            TlowR011S0p4MDQwMThNb2xIUjI5NUEKs6E1zb9PbJm06Lso9zxsa5PRjEIOGi9z
            g97FC415NBptevFpWtoa83PAIdW0IOtstSx9v6zVMgxMFVGFt7Q8pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-13T23:24:18Z"
    mac: ENC[AES256_GCM,data:j38veQK8NRQ34gxga2LpmVAvtcsI3BTcuJxgHVKkgmEECOskjHSrhI/S2Px5EmW2w1hl3/oXvrdRSzWbZisD/rmZEukvTUajAdvej0RSQbXxiUdm3RTT3ieqbRSpjlqJU7s19TQBBusGwNOJ/GRJFH8MXszF1wNED3Izz9f8b0M=,iv:wN5PuKhNDTKwpnUud7RBOYMj1Rh50ZJ+v/aeI+1xgXQ=,tag:EEuf5zbHlpOxvI4mwsLpQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
