tailscale: ENC[AES256_GCM,data:S6W2rq8zaINObYKa3QgbXNnwi5lxprXlS9xlkf8r3qd7D5ccND9dwlPCic68ptHNwkPvdqncfcsAdMx/Wnk=,iv:F0fWGiYvb0jFrZjBV1uvxlUWm/T3gjrBfY2NMwP0lS4=,tag:T3HtFpubMIzg9kYu9L/PXQ==,type:str]
users:
    joshua: ENC[AES256_GCM,data:lwvAepBgR7kFJDhcRHOyNy/KdwXX1xQiA7jnxxOkYwfylELGr9SuTwqDraAyt+seesAbj1PAN7Ncr89Lg3qVdZelvwcFlHklvQ==,iv:g36cfRZcv8710lrwI4cy0GPQ9fndhgEZn75uk06xF+M=,tag:GduYdkT8IFjIo3VJ5oA7pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1de6wyynhrf0mjxg85dq8layuwqudj527pfv9l4v6sdcu8a5w0ggqedl40j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEb1RjbmFkSVJWSWlxYlV5
            bW1nK1FnbUFlOGMxL1pIQlZyank4YndHY2pJCkR4M0lPUXVPVm95NnJidUwzc1pY
            ZURiaTAzRjJkY2tEYTJpcnlkZUZuK0EKLS0tIEdxMkNvSjJKZTFURTBTRXN3eDk4
            WXZwVGRCaGswWEpRM0Z0RHVwMmZrdmsKp5x/DWHTAht8DmcjOyN1DHXX7OvC7peA
            D0VkmmhL6rIqadY6HvIBku/FwMner+j0U8yy3zlad4Qhs2rWd/Qu+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-07T21:12:37Z"
    mac: ENC[AES256_GCM,data:3xv+jwprzySGOnnVvgimVelbdMNd/OI2ubrS3NTV1TyZJiha6DSvQEvO7vH7+zXL65KKYUVCRW8eiH9LQQxZ0rdrrgCmi7iE5l0qBJfR04FMhEorX6F7qWI2ZVIqD1cdVpBb9MV+4CkNhU0m+jiM3dCjFvYRxKIHtXln8Fe0CNw=,iv:OW4yfc+kDWa7HTaUN/CPFClq/HTXIH9wnYkNeR1kiq4=,tag:9fu35Bu3qPdto0WGn49+Dg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
