{
  config,
  lib,
  pkgs,
  ...
}: {
  options.meta = {
    criticalDataPaths = lib.mkOption {
      type = with lib.types; listOf str;
      description = "A list of paths to critical data that must be backed up.";
      default = [
        /*
          Note that these paths are relative to the container. Furthermore, some
          paths are generated by the `meta.beforeBackup` script as there may
          exist running processes which have not flushed their writes yet.
        */
        "/var/lib/vaultwarden"
      ];
      readOnly = true;
    };

    beforeBackup = lib.mkOption {
      type = lib.types.str;
      description = "A script which is run before remote off-site backup.";
      default = ''
        # Asks the running Vaultwarden instance to create a backup.
        ${pkgs.procps}/bin/pkill -USR1 vaultwarden
      '';
    };

    afterBackup = lib.mkOption {
      type = lib.types.str;
      description = "A script which is run after remote off-site backup.";
      default = "";
    };
  };

  config = {
    services.dnsmasq = {
      enable = true;
      resolveLocalQueries = false;

      settings = {
        server = ["1.1.1.1" "1.0.0.1"];
        address = [
          "/forge.joshprk.me/100.87.235.15"
          "/vault.joshprk.me/100.87.235.15"
        ];
        no-resolv = true;
      };
    };

    services.vaultwarden = {
      enable = true;
      environmentFile = config.age.secrets.vault-env.path;

      config = {
        DOMAIN = "https://vault.joshprk.me";
        SIGNUPS_ALLOWED = false;
        ROCKET_ADDRESS = "127.0.0.1";
        ROCKET_PORT = 8222;
      };
    };

    services.restic.backups = {
      gdrive = {
        repository = "rclone:drive:backups";
        initialize = true;
        passwordFile = config.age.secrets.restic-pass.path;
        paths = config.meta.criticalDataPaths;
        timerConfig.onCalendar = "friday 3:00";
        backupPrepareCommand = config.meta.beforeBackup;
        backupCleanupCommand = config.meta.afterBackup;

        rcloneConfig = {
          type = "drive";
          scope = "drive.file";
          root_folder_id = "1ph4V6LDWt6EBQPaEpy9naYXTPecKFdmY";
          service_account_file = config.age.secrets.restic-gdrive.path;
        };
      };
    };

    system.stateVersion = "25.11";
  };
}
